from requests import get, put, delete, post
print("login admin")
print(post('http://localhost:5000/users/api/session/admin', data={'password':'admin'}).json())
print("admin data")
print(get('http://localhost:5000/users/api/admin', data = {'username': 'admin'}).json())
print("Admin logs out")
print(put('http://localhost:5000/users/api/session/admin').json())
print("Logged out admin tries to hire Ted")
print(post('http://localhost:5000/users/api/admin', data={'username': 'Ted', 'password':'somesupersafepassword', 'role': 'manager'}).json())
print("Admin logs in again")
print(post('http://localhost:5000/users/api/session/admin', data={'password':'admin'}).json())
print("Hire Ted, the manager")
print(post('http://localhost:5000/users/api/admin', data={'username': 'Ted', 'password':'somesupersafepassword', 'role': 'manager'}).json())
print("Admin gets infos of Ted")
print(get('http://localhost:5000/users/api/admin', data={'username': 'Ted'}).json())
print("Ted logs in")
print(post('http://localhost:5000/users/api/session/Ted', data={'password':'somesupersafepassword'}).json())
print("Ted gets infos of admin")
print(get('http://localhost:5000/users/api/Ted', data={'username': 'admin'}).json())
print("Ted tries to hire Berta, the secretary.")
print(post('http://localhost:5000/users/api/Ted', data={'username': 'Berta', 'password':'1234', 'role': 'secretary'}).json())
print("Admin gets infos of Berta, the secretary")
print(get('http://localhost:5000/users/api/admin', data={"username":"Berta"}).json())
print("Admin hires Berta, the secretary")
print(post('http://localhost:5000/users/api/admin', data={'username': 'Berta', 'password':'1234', 'role': 'secretary'}).json())
print("Admin accesses Berta's data")
print(get('http://localhost:5000/users/api/admin', data={"username":"Berta"}).json())
print("Ted got mad. He wants to fire Berta, the secretary, now.")
print(delete('http://localhost:5000/users/api/Ted', data = {'username': 'Berta'}).json())
print("Admin accesses Berta's data")
print(get('http://localhost:5000/users/api/admin', data={"username":"Berta"}).json())
print("Admin agrees with Ted and fires Berta, the secretary now.")
print(delete('http://localhost:5000/users/api/admin', data = {'username': 'Berta'}).json())
print("Admin accesses Berta's data")
print(get('http://localhost:5000/users/api/admin', data={"username":"Berta"}).json())
print("Ted logs out")
print(put('http://localhost:5000/users/api/session/Ted').json())
print("Ted logs in with wrong password")
print(post('http://localhost:5000/users/api/session/Ted', data={'password':'somewrongpassword'}).json())
print("Admin wants to get data from Ted now.")
print("Admin logs in again")
print(post('http://localhost:5000/users/api/session/admin', data={'password':'admin'}).json())
print("Hire Ted, the manager")
print(post('http://localhost:5000/users/api/admin', data={'username': 'Ted', 'password':'somesupersafepassword', 'role': 'manager'}).json())
print("Ted logs in")
print(post('http://localhost:5000/users/api/session/Ted', data={'password':'somesupersafepassword'}).json())
print(get('http://localhost:5000/users/api/admin', data={"username":"Ted"}).json())
print('Ted wants to change his password.')
print(put('http://localhost:5000/users/api/Ted', data={'new_password': 'superhotnewpassword'}).json())
print("Admin wants to get data from Ted now.")
print(get('http://localhost:5000/users/api/admin', data={"username":"Ted"}).json())
